language:  node_js
node_js:
  - "7"

# Setup for Headless Chrome Testing
before_script:
  - npm run dev & 
  - sleep 10
script: 
  - npm run test

#Install and Use Chrome
addons:
  chrome: stable
dist: trusty
